# bundle install
source 'https://rubygems.org'

#【 cucumber 组 件 】
group :test do
	gem 'cucumber', '1.3.15'
	gem 'rspec-expectations', '3.0.2'
end


#【 selenium 组 件 】
gem 'selenium', '0.2.11'
gem 'selenium-webdriver', '2.42.0'


#【 watir 组 件 】
gem 'watir', '5.0.0'
gem 'watir-webdriver', '0.6.10'
gem 'watir-webdriver-performance', '0.2.4'


#【 page-object 组 件 】
gem 'page-object', '1.0.2'


# 【 rspec 组 件 】
gem 'rspec', '3.0.0'
gem 'rspec-core', '3.0.3'
gem 'rspec-mocks', '3.0.2'
gem 'rspec-support', '3.0.2'



#【 统 计 测 试 代 码 覆 盖 率 】
gem 'simplecov', '0.9.1'





